theme: minima

title: estoy haciendo el CURSO
author: RDearmas
email: rodrigo@domain.com
description: > # this means to ignore newlines until "baseurl:"
  esta es la descripciondela weeee

# social links
twitter_username: rodrigolala # DO NOT include the @ character, or else the build will fail!
github_username:  rdearmas # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
